export const GET_ALL_TRANSACTIONS_REQUEST = "GET_ALL_TRANSACTIONS_REQUEST";
export const GET_ALL_TRANSACTIONS_SUCCESS = "GET_ALL_TRANSACTIONS_SUCCESS";
export const GET_ALL_TRANSACTIONS_FAIL = "GET_ALL_TRANSACTIONS_FAIL";

export const GET_ANALYTICS_SUMMARY_REQUEST = "GET_ANALYTICS_SUMMARY_REQUEST";
export const GET_ANALYTICS_SUMMARY_SUCCESS = "GET_ANALYTICS_SUMMARY_SUCCESS";
export const GET_ANALYTICS_SUMMARY_FAIL = "GET_ANALYTICS_SUMMARY_FAIL";

export const GET_SALES_BY_CATEGORY_REQUEST = "GET_SALES_BY_CATEGORY_REQUEST";
export const GET_SALES_BY_CATEGORY_SUCCESS = "GET_SALES_BY_CATEGORY_SUCCESS";
export const GET_SALES_BY_CATEGORY_FAIL = "GET_SALES_BY_CATEGORY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
