export const ART_CREATE_REQUEST = "ART_CREATE_REQUEST";
export const ART_CREATE_SUCCESS = "ART_CREATE_SUCCESS";
export const ART_CREATE_FAIL = "ART_CREATE_FAIL";

export const ART_UPDATE_REQUEST = "ART_UPDATE_REQUEST";
export const ART_UPDATE_SUCCESS = "ART_UPDATE_SUCCESS";
export const ART_UPDATE_FAIL = "ART_UPDATE_FAIL";

export const ART_DELETE_REQUEST = "ART_DELETE_REQUEST";
export const ART_DELETE_SUCCESS = "ART_DELETE_SUCCESS";
export const ART_DELETE_FAIL = "ART_DELETE_FAIL";

export const ART_LIST_REQUEST = "ART_LIST_REQUEST";
export const ART_LIST_SUCCESS = "ART_LIST_SUCCESS";
export const ART_LIST_FAIL = "ART_LIST_FAIL";

export const ART_DETAILS_REQUEST = "ART_DETAILS_REQUEST";
export const ART_DETAILS_SUCCESS = "ART_DETAILS_SUCCESS";
export const ART_DETAILS_FAIL = "ART_DETAILS_FAIL";

export const PUBLIC_ART_LIST_REQUEST = "PUBLIC_ART_LIST_REQUEST";
export const PUBLIC_ART_LIST_SUCCESS = "PUBLIC_ART_LIST_SUCCESS";
export const PUBLIC_ART_LIST_FAIL = "PUBLIC_ART_LIST_FAIL";

export const PUBLIC_ART_DETAILS_REQUEST = "PUBLIC_ART_DETAILS_REQUEST";
export const PUBLIC_ART_DETAILS_SUCCESS = "PUBLIC_ART_DETAILS_SUCCESS";
export const PUBLIC_ART_DETAILS_FAIL = "PUBLIC_ART_DETAILS_FAIL";
