export const WALLET_DETAILS_REQUEST = "WALLET_DETAILS_REQUEST";
export const WALLET_DETAILS_SUCCESS = "WALLET_DETAILS_SUCCESS";
export const WALLET_DETAILS_FAIL = "WALLET_DETAILS_FAIL";

export const ADD_FUNDS_REQUEST = "ADD_FUNDS_REQUEST";
export const ADD_FUNDS_SUCCESS = "ADD_FUNDS_SUCCESS";
export const ADD_FUNDS_FAIL = "ADD_FUNDS_FAIL";

export const TRANSFER_FUNDS_REQUEST = "TRANSFER_FUNDS_REQUEST";
export const TRANSFER_FUNDS_SUCCESS = "TRANSFER_FUNDS_SUCCESS";
export const TRANSFER_FUNDS_FAIL = "TRANSFER_FUNDS_FAIL";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
